// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: telemetry.proto

package telemetry

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpuCore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Percent       float64                `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`
	Mhz           float64                `protobuf:"fixed64,3,opt,name=mhz,proto3" json:"mhz,omitempty"` // nominal/current if available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuCore) Reset() {
	*x = CpuCore{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuCore) ProtoMessage() {}

func (x *CpuCore) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuCore.ProtoReflect.Descriptor instead.
func (*CpuCore) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *CpuCore) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CpuCore) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *CpuCore) GetMhz() float64 {
	if x != nil {
		return x.Mhz
	}
	return 0
}

type CpuSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPercent  float64                `protobuf:"fixed64,1,opt,name=total_percent,json=totalPercent,proto3" json:"total_percent,omitempty"`
	Cores         []*CpuCore             `protobuf:"bytes,2,rep,name=cores,proto3" json:"cores,omitempty"`
	Logical       uint32                 `protobuf:"varint,3,opt,name=logical,proto3" json:"logical,omitempty"`
	Physical      uint32                 `protobuf:"varint,4,opt,name=physical,proto3" json:"physical,omitempty"`
	ModelName     string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuSummary) Reset() {
	*x = CpuSummary{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuSummary) ProtoMessage() {}

func (x *CpuSummary) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuSummary.ProtoReflect.Descriptor instead.
func (*CpuSummary) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *CpuSummary) GetTotalPercent() float64 {
	if x != nil {
		return x.TotalPercent
	}
	return 0
}

func (x *CpuSummary) GetCores() []*CpuCore {
	if x != nil {
		return x.Cores
	}
	return nil
}

func (x *CpuSummary) GetLogical() uint32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *CpuSummary) GetPhysical() uint32 {
	if x != nil {
		return x.Physical
	}
	return 0
}

func (x *CpuSummary) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

type LoadAvg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load1         float64                `protobuf:"fixed64,1,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5         float64                `protobuf:"fixed64,2,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15        float64                `protobuf:"fixed64,3,opt,name=load15,proto3" json:"load15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAvg) Reset() {
	*x = LoadAvg{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAvg) ProtoMessage() {}

func (x *LoadAvg) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAvg.ProtoReflect.Descriptor instead.
func (*LoadAvg) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *LoadAvg) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *LoadAvg) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *LoadAvg) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

type Mem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	Available     uint64                 `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,5,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mem) Reset() {
	*x = Mem{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mem) ProtoMessage() {}

func (x *Mem) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mem.ProtoReflect.Descriptor instead.
func (*Mem) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *Mem) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Mem) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Mem) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *Mem) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *Mem) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type Swap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Swap) Reset() {
	*x = Swap{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Swap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swap) ProtoMessage() {}

func (x *Swap) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swap.ProtoReflect.Descriptor instead.
func (*Swap) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *Swap) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Swap) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Swap) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *Swap) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type FsUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mountpoint    string                 `protobuf:"bytes,1,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Fstype        string                 `protobuf:"bytes,2,opt,name=fstype,proto3" json:"fstype,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,5,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,6,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsUsage) Reset() {
	*x = FsUsage{}
	mi := &file_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsUsage) ProtoMessage() {}

func (x *FsUsage) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsUsage.ProtoReflect.Descriptor instead.
func (*FsUsage) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *FsUsage) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *FsUsage) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *FsUsage) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FsUsage) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *FsUsage) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *FsUsage) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type DiskIO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadBytes     uint64                 `protobuf:"varint,2,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes    uint64                 `protobuf:"varint,3,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	ReadCount     uint64                 `protobuf:"varint,4,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	WriteCount    uint64                 `protobuf:"varint,5,opt,name=write_count,json=writeCount,proto3" json:"write_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskIO) Reset() {
	*x = DiskIO{}
	mi := &file_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIO) ProtoMessage() {}

func (x *DiskIO) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIO.ProtoReflect.Descriptor instead.
func (*DiskIO) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *DiskIO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskIO) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *DiskIO) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *DiskIO) GetReadCount() uint64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *DiskIO) GetWriteCount() uint64 {
	if x != nil {
		return x.WriteCount
	}
	return 0
}

type NetIF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hwaddr        string                 `protobuf:"bytes,2,opt,name=hwaddr,proto3" json:"hwaddr,omitempty"`
	Addrs         []string               `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	BytesSent     uint64                 `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     uint64                 `protobuf:"varint,5,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	PacketsSent   uint64                 `protobuf:"varint,6,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsRecv   uint64                 `protobuf:"varint,7,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	Errin         uint64                 `protobuf:"varint,8,opt,name=errin,proto3" json:"errin,omitempty"`
	Errout        uint64                 `protobuf:"varint,9,opt,name=errout,proto3" json:"errout,omitempty"`
	Dropin        uint64                 `protobuf:"varint,10,opt,name=dropin,proto3" json:"dropin,omitempty"`
	Dropout       uint64                 `protobuf:"varint,11,opt,name=dropout,proto3" json:"dropout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetIF) Reset() {
	*x = NetIF{}
	mi := &file_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetIF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetIF) ProtoMessage() {}

func (x *NetIF) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetIF.ProtoReflect.Descriptor instead.
func (*NetIF) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *NetIF) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetIF) GetHwaddr() string {
	if x != nil {
		return x.Hwaddr
	}
	return ""
}

func (x *NetIF) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *NetIF) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetIF) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *NetIF) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetIF) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

func (x *NetIF) GetErrin() uint64 {
	if x != nil {
		return x.Errin
	}
	return 0
}

func (x *NetIF) GetErrout() uint64 {
	if x != nil {
		return x.Errout
	}
	return 0
}

func (x *NetIF) GetDropin() uint64 {
	if x != nil {
		return x.Dropin
	}
	return 0
}

func (x *NetIF) GetDropout() uint64 {
	if x != nil {
		return x.Dropout
	}
	return 0
}

type HostInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hostname             string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os                   string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Platform             string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformFamily       string                 `protobuf:"bytes,4,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`
	PlatformVersion      string                 `protobuf:"bytes,5,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	KernelVersion        string                 `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	UptimeSec            uint64                 `protobuf:"varint,7,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	BootTime             uint64                 `protobuf:"varint,8,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	VirtualizationSystem string                 `protobuf:"bytes,9,opt,name=virtualization_system,json=virtualizationSystem,proto3" json:"virtualization_system,omitempty"`
	VirtualizationRole   string                 `protobuf:"bytes,10,opt,name=virtualization_role,json=virtualizationRole,proto3" json:"virtualization_role,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *HostInfo) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *HostInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *HostInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *HostInfo) GetUptimeSec() uint64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

func (x *HostInfo) GetBootTime() uint64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

func (x *HostInfo) GetVirtualizationSystem() string {
	if x != nil {
		return x.VirtualizationSystem
	}
	return ""
}

func (x *HostInfo) GetVirtualizationRole() string {
	if x != nil {
		return x.VirtualizationRole
	}
	return ""
}

type Temperature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorKey     string                 `protobuf:"bytes,1,opt,name=sensor_key,json=sensorKey,proto3" json:"sensor_key,omitempty"`
	Temperature   float64                `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Critical      float64                `protobuf:"fixed64,4,opt,name=critical,proto3" json:"critical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	mi := &file_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *Temperature) GetSensorKey() string {
	if x != nil {
		return x.SensorKey
	}
	return ""
}

func (x *Temperature) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Temperature) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Temperature) GetCritical() float64 {
	if x != nil {
		return x.Critical
	}
	return 0
}

type Proc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float32                `protobuf:"fixed32,5,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	Rss           uint64                 `protobuf:"varint,6,opt,name=rss,proto3" json:"rss,omitempty"`
	Nice          int32                  `protobuf:"varint,7,opt,name=nice,proto3" json:"nice,omitempty"`
	Threads       int32                  `protobuf:"varint,8,opt,name=threads,proto3" json:"threads,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proc) Reset() {
	*x = Proc{}
	mi := &file_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proc) ProtoMessage() {}

func (x *Proc) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proc.ProtoReflect.Descriptor instead.
func (*Proc) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *Proc) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Proc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Proc) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Proc) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Proc) GetMemPercent() float32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *Proc) GetRss() uint64 {
	if x != nil {
		return x.Rss
	}
	return 0
}

func (x *Proc) GetNice() int32 {
	if x != nil {
		return x.Nice
	}
	return 0
}

func (x *Proc) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *Proc) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Snapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CollectedUnixMs int64                  `protobuf:"varint,1,opt,name=collected_unix_ms,json=collectedUnixMs,proto3" json:"collected_unix_ms,omitempty"`
	Cpu             *CpuSummary            `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Load            *LoadAvg               `protobuf:"bytes,3,opt,name=load,proto3" json:"load,omitempty"`
	Mem             *Mem                   `protobuf:"bytes,4,opt,name=mem,proto3" json:"mem,omitempty"`
	Swap            *Swap                  `protobuf:"bytes,5,opt,name=swap,proto3" json:"swap,omitempty"`
	Filesystems     []*FsUsage             `protobuf:"bytes,6,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	DiskIo          []*DiskIO              `protobuf:"bytes,7,rep,name=disk_io,json=diskIo,proto3" json:"disk_io,omitempty"`
	Net             []*NetIF               `protobuf:"bytes,8,rep,name=net,proto3" json:"net,omitempty"`
	Host            *HostInfo              `protobuf:"bytes,9,opt,name=host,proto3" json:"host,omitempty"`
	Temperatures    []*Temperature         `protobuf:"bytes,10,rep,name=temperatures,proto3" json:"temperatures,omitempty"`
	TopProcs        []*Proc                `protobuf:"bytes,11,rep,name=top_procs,json=topProcs,proto3" json:"top_procs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_telemetry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{11}
}

func (x *Snapshot) GetCollectedUnixMs() int64 {
	if x != nil {
		return x.CollectedUnixMs
	}
	return 0
}

func (x *Snapshot) GetCpu() *CpuSummary {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Snapshot) GetLoad() *LoadAvg {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *Snapshot) GetMem() *Mem {
	if x != nil {
		return x.Mem
	}
	return nil
}

func (x *Snapshot) GetSwap() *Swap {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *Snapshot) GetFilesystems() []*FsUsage {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

func (x *Snapshot) GetDiskIo() []*DiskIO {
	if x != nil {
		return x.DiskIo
	}
	return nil
}

func (x *Snapshot) GetNet() []*NetIF {
	if x != nil {
		return x.Net
	}
	return nil
}

func (x *Snapshot) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Snapshot) GetTemperatures() []*Temperature {
	if x != nil {
		return x.Temperatures
	}
	return nil
}

func (x *Snapshot) GetTopProcs() []*Proc {
	if x != nil {
		return x.TopProcs
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalMs    uint32                 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	TopN          uint32                 `protobuf:"varint,2,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_telemetry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *SubscribeRequest) GetTopN() uint32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\"E\n" +
	"\aCpuCore\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\x12\x10\n" +
	"\x03mhz\x18\x03 \x01(\x01R\x03mhz\"\xb0\x01\n" +
	"\n" +
	"CpuSummary\x12#\n" +
	"\rtotal_percent\x18\x01 \x01(\x01R\ftotalPercent\x12(\n" +
	"\x05cores\x18\x02 \x03(\v2\x12.telemetry.CpuCoreR\x05cores\x12\x18\n" +
	"\alogical\x18\x03 \x01(\rR\alogical\x12\x1a\n" +
	"\bphysical\x18\x04 \x01(\rR\bphysical\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\"M\n" +
	"\aLoadAvg\x12\x14\n" +
	"\x05load1\x18\x01 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x02 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\x03 \x01(\x01R\x06load15\"\x84\x01\n" +
	"\x03Mem\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\x04R\tavailable\x12!\n" +
	"\fused_percent\x18\x05 \x01(\x01R\vusedPercent\"g\n" +
	"\x04Swap\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12!\n" +
	"\fused_percent\x18\x04 \x01(\x01R\vusedPercent\"\xa2\x01\n" +
	"\aFsUsage\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x01 \x01(\tR\n" +
	"mountpoint\x12\x16\n" +
	"\x06fstype\x18\x02 \x01(\tR\x06fstype\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x04 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x05 \x01(\x04R\x04free\x12!\n" +
	"\fused_percent\x18\x06 \x01(\x01R\vusedPercent\"\x9c\x01\n" +
	"\x06DiskIO\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x02 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x03 \x01(\x04R\n" +
	"writeBytes\x12\x1d\n" +
	"\n" +
	"read_count\x18\x04 \x01(\x04R\treadCount\x12\x1f\n" +
	"\vwrite_count\x18\x05 \x01(\x04R\n" +
	"writeCount\"\xad\x02\n" +
	"\x05NetIF\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06hwaddr\x18\x02 \x01(\tR\x06hwaddr\x12\x14\n" +
	"\x05addrs\x18\x03 \x03(\tR\x05addrs\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x04R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x05 \x01(\x04R\tbytesRecv\x12!\n" +
	"\fpackets_sent\x18\x06 \x01(\x04R\vpacketsSent\x12!\n" +
	"\fpackets_recv\x18\a \x01(\x04R\vpacketsRecv\x12\x14\n" +
	"\x05errin\x18\b \x01(\x04R\x05errin\x12\x16\n" +
	"\x06errout\x18\t \x01(\x04R\x06errout\x12\x16\n" +
	"\x06dropin\x18\n" +
	" \x01(\x04R\x06dropin\x12\x18\n" +
	"\adropout\x18\v \x01(\x04R\adropout\"\xef\x02\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12'\n" +
	"\x0fplatform_family\x18\x04 \x01(\tR\x0eplatformFamily\x12)\n" +
	"\x10platform_version\x18\x05 \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\a \x01(\x04R\tuptimeSec\x12\x1b\n" +
	"\tboot_time\x18\b \x01(\x04R\bbootTime\x123\n" +
	"\x15virtualization_system\x18\t \x01(\tR\x14virtualizationSystem\x12/\n" +
	"\x13virtualization_role\x18\n" +
	" \x01(\tR\x12virtualizationRole\"~\n" +
	"\vTemperature\x12\x1d\n" +
	"\n" +
	"sensor_key\x18\x01 \x01(\tR\tsensorKey\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x01R\vtemperature\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x1a\n" +
	"\bcritical\x18\x04 \x01(\x01R\bcritical\"\xe2\x01\n" +
	"\x04Proc\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x05 \x01(\x02R\n" +
	"memPercent\x12\x10\n" +
	"\x03rss\x18\x06 \x01(\x04R\x03rss\x12\x12\n" +
	"\x04nice\x18\a \x01(\x05R\x04nice\x12\x18\n" +
	"\athreads\x18\b \x01(\x05R\athreads\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\xe7\x03\n" +
	"\bSnapshot\x12*\n" +
	"\x11collected_unix_ms\x18\x01 \x01(\x03R\x0fcollectedUnixMs\x12'\n" +
	"\x03cpu\x18\x02 \x01(\v2\x15.telemetry.CpuSummaryR\x03cpu\x12&\n" +
	"\x04load\x18\x03 \x01(\v2\x12.telemetry.LoadAvgR\x04load\x12 \n" +
	"\x03mem\x18\x04 \x01(\v2\x0e.telemetry.MemR\x03mem\x12#\n" +
	"\x04swap\x18\x05 \x01(\v2\x0f.telemetry.SwapR\x04swap\x124\n" +
	"\vfilesystems\x18\x06 \x03(\v2\x12.telemetry.FsUsageR\vfilesystems\x12*\n" +
	"\adisk_io\x18\a \x03(\v2\x11.telemetry.DiskIOR\x06diskIo\x12\"\n" +
	"\x03net\x18\b \x03(\v2\x10.telemetry.NetIFR\x03net\x12'\n" +
	"\x04host\x18\t \x01(\v2\x13.telemetry.HostInfoR\x04host\x12:\n" +
	"\ftemperatures\x18\n" +
	" \x03(\v2\x16.telemetry.TemperatureR\ftemperatures\x12,\n" +
	"\ttop_procs\x18\v \x03(\v2\x0f.telemetry.ProcR\btopProcs\"H\n" +
	"\x10SubscribeRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\rR\n" +
	"intervalMs\x12\x13\n" +
	"\x05top_n\x18\x02 \x01(\rR\x04topN2S\n" +
	"\tTelemetry\x12F\n" +
	"\x10SubscribeMetrics\x12\x1b.telemetry.SubscribeRequest\x1a\x13.telemetry.Snapshot0\x01B#Z!monitor/proto/telemetry;telemetryb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_telemetry_proto_goTypes = []any{
	(*CpuCore)(nil),          // 0: telemetry.CpuCore
	(*CpuSummary)(nil),       // 1: telemetry.CpuSummary
	(*LoadAvg)(nil),          // 2: telemetry.LoadAvg
	(*Mem)(nil),              // 3: telemetry.Mem
	(*Swap)(nil),             // 4: telemetry.Swap
	(*FsUsage)(nil),          // 5: telemetry.FsUsage
	(*DiskIO)(nil),           // 6: telemetry.DiskIO
	(*NetIF)(nil),            // 7: telemetry.NetIF
	(*HostInfo)(nil),         // 8: telemetry.HostInfo
	(*Temperature)(nil),      // 9: telemetry.Temperature
	(*Proc)(nil),             // 10: telemetry.Proc
	(*Snapshot)(nil),         // 11: telemetry.Snapshot
	(*SubscribeRequest)(nil), // 12: telemetry.SubscribeRequest
}
var file_telemetry_proto_depIdxs = []int32{
	0,  // 0: telemetry.CpuSummary.cores:type_name -> telemetry.CpuCore
	1,  // 1: telemetry.Snapshot.cpu:type_name -> telemetry.CpuSummary
	2,  // 2: telemetry.Snapshot.load:type_name -> telemetry.LoadAvg
	3,  // 3: telemetry.Snapshot.mem:type_name -> telemetry.Mem
	4,  // 4: telemetry.Snapshot.swap:type_name -> telemetry.Swap
	5,  // 5: telemetry.Snapshot.filesystems:type_name -> telemetry.FsUsage
	6,  // 6: telemetry.Snapshot.disk_io:type_name -> telemetry.DiskIO
	7,  // 7: telemetry.Snapshot.net:type_name -> telemetry.NetIF
	8,  // 8: telemetry.Snapshot.host:type_name -> telemetry.HostInfo
	9,  // 9: telemetry.Snapshot.temperatures:type_name -> telemetry.Temperature
	10, // 10: telemetry.Snapshot.top_procs:type_name -> telemetry.Proc
	12, // 11: telemetry.Telemetry.SubscribeMetrics:input_type -> telemetry.SubscribeRequest
	11, // 12: telemetry.Telemetry.SubscribeMetrics:output_type -> telemetry.Snapshot
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
